-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-04 13:14:25 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Category 
    ( 
     category_id   INTEGER  NOT NULL , 
     category_name  VARCHAR2 (30) , 
     parent_id      INTEGER 
    ) 
;

ALTER TABLE Category 
    ADD CONSTRAINT Category_PK PRIMARY KEY ( category_id ) ;

CREATE TABLE Customer 
    ( 
     customer_id       INTEGER  NOT NULL , 
     first_name        VARCHAR2 (30) , 
     last_name         VARCHAR2 (30) , 
     email             VARCHAR2 (50) , 
     city              VARCHAR2 (30) , 
     registration_date DATE 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( customer_id ) ;

CREATE TABLE Inventory_log 
    ( 
     log_id             INTEGER  NOT NULL , 
     change_amount      NUMBER , 
     reason             VARCHAR2 (20) , 
     log_date           DATE , 
     product_id         INTEGER 
    ) 
;

ALTER TABLE Inventory_log 
    ADD CONSTRAINT Inventory_log_PK PRIMARY KEY ( log_id ) ;

CREATE TABLE "Order" 
    ( 
     order_id             INTEGER  NOT NULL , 
     order_date           DATE , 
     status               VARCHAR2 (20) , 
     customer_id          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE "Order" 
    ADD CONSTRAINT Order_PK PRIMARY KEY ( order_id ) ;

CREATE TABLE Order_item 
    ( 
     order_item_id      INTEGER  NOT NULL , 
     quantity           INTEGER , 
     unit_price         NUMBER , 
     product_id         INTEGER , 
     order_id           INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Order_item 
    ADD CONSTRAINT Order_item_PK PRIMARY KEY ( order_item_id ) ;

CREATE TABLE Product 
    ( 
     product_id           INTEGER  NOT NULL , 
     product_name         VARCHAR2 (30) , 
     list_price           NUMBER , 
     cost_price           NUMBER , 
     sku                  VARCHAR2 (20) , 
     category_id          INTEGER 
    ) 
;

ALTER TABLE Product 
    ADD CONSTRAINT Product_PK PRIMARY KEY ( product_id ) ;

ALTER TABLE Category 
    ADD CONSTRAINT Category_Category_FK FOREIGN KEY 
    ( 
     parent_id
    ) 
    REFERENCES Category 
    ( 
     category_id
    ) 
;

ALTER TABLE Inventory_log 
    ADD CONSTRAINT Inventory_log_Product_FK FOREIGN KEY 
    ( 
     product_id
    ) 
    REFERENCES Product 
    ( 
     product_id
    ) 
;

ALTER TABLE "Order" 
    ADD CONSTRAINT Order_Customer_FK FOREIGN KEY 
    ( 
     customer_id
    ) 
    REFERENCES Customer 
    ( 
     customer_id
    ) 
;

ALTER TABLE Order_item 
    ADD CONSTRAINT Order_item_Order_FK FOREIGN KEY 
    ( 
     order_id
    ) 
    REFERENCES "Order" 
    ( 
     order_id
    ) 
;

ALTER TABLE Order_item 
    ADD CONSTRAINT Order_item_Product_FK FOREIGN KEY 
    ( 
     product_id
    ) 
    REFERENCES Product 
    ( 
     product_id
    ) 
;

ALTER TABLE Product 
    ADD CONSTRAINT Product_Category_FK FOREIGN KEY 
    ( 
     category_id
    ) 
    REFERENCES Category 
    ( 
     category_id
    ) 
    ON DELETE SET NULL 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            6
-- CREATE INDEX                            0
-- ALTER TABLE                            12
-- CREATE VIEW                             0
-- ALTER VIEW                              0
-- CREATE PACKAGE                          0
-- CREATE PACKAGE BODY                     0
-- CREATE PROCEDURE                        0
-- CREATE FUNCTION                         0
-- CREATE TRIGGER                          0
-- ALTER TRIGGER                           0
-- CREATE COLLECTION TYPE                  0
-- CREATE STRUCTURED TYPE                  0
-- CREATE STRUCTURED TYPE BODY             0
-- CREATE CLUSTER                          0
-- CREATE CONTEXT                          0
-- CREATE DATABASE                         0
-- CREATE DIMENSION                        0
-- CREATE DIRECTORY                        0
-- CREATE DISK GROUP                       0
-- CREATE ROLE                             0
-- CREATE ROLLBACK SEGMENT                 0
-- CREATE SEQUENCE                         0
-- CREATE MATERIALIZED VIEW                0
-- CREATE MATERIALIZED VIEW LOG            0
-- CREATE SYNONYM                          0
-- CREATE TABLESPACE                       0
-- CREATE USER                             0
-- 
-- DROP TABLESPACE                         0
-- DROP DATABASE                           0
-- 
-- REDACTION POLICY                        0
-- 
-- ORDS DROP SCHEMA                        0
-- ORDS ENABLE SCHEMA                      0
-- ORDS ENABLE OBJECT                      0
-- 
-- ERRORS                                  0
-- WARNINGS                                0